export const FALLBACK_PROFILE = {
  id: "artist-suhail",
  nameAr: "الخطاط سهيل نصر",
  nameEn: "Suhail Nasr",
  titleAr: "خطاط وفنان للحرف العربي",
  titleEn: "Arabic Calligrapher & Lettering Artist",
  bioAr:
    "خطاط عربي مقيم في الرياض، متفرد في نقل الحرف العربي من الورق التقليدي إلى أبعاد وخامات حية كالحفر على الزجاج، الحرق على الخشب، ونقش الإهداءات على السبح والأكواب والمخمل، ليكون العمل أثراً باقياً يفيض بالأصالة والجمال المعاصر.",
  bioEn:
    "Saudi-based Arabic calligrapher and lettering artist working from Riyadh, specializing in transcending traditional paper onto bespoke living materials including glass engraving, wood burning, prayer beads, and velvet.",
  philosophyAr: "حين يصبح الحرف أثراً.",
  philosophyEn: "When the letter becomes an imprint.",
  profileImage: "/images/suhail-portrait.jpg",
  coverImage: "/images/hero-calligraphy.jpg",
  phone: "+966 55 317 2286",
  whatsapp: "966553172286",
  email: "contact@suhailnasr.art",
  snapchatUrl: "https://www.snapchat.com/@Sohilnasr7",
  instagramUrl: "https://www.instagram.com/sohil.nassr",
  tiktokUrl: "https://www.tiktok.com/@.sohil_nassr77",
  location: "الرياض، المملكة العربية السعودية",
  seoTitle: "الخطاط سهيل نصر — منصة الخط العربي والأتيليه الفني",
  seoDescription:
    "المعرض الرسمي للخطاط سهيل نصر في الرياض. استعراض الأعمال الفنية على الزجاج والخشب والسبح، وطلب الأعمال الحروفية المخصصة.",
};

export const FALLBACK_WORKS = [
  {
    id: "work-1",
    titleAr: "رؤية وطن ٢٠٣٠ — جدارية الفخر والريادة",
    titleEn: "Saudi Vision 2030 Landmark Mural",
    slug: "saudi-vision-2030-mural",
    excerptAr: "لوحة جدارية بالخط الثلث المركب مستلهمة من رؤية المملكة العربية السعودية الطموحة 2030.",
    descriptionAr: "جدارية وطنية مهيبة تخلد عبارات العز والنهضة بريشة الخطاط سهيل نصر مع تذهيب عيار 24.",
    coverImage: "/images/suhail-vision-2030.png",
    featured: true,
    year: 2024,
    dimensions: "180 × 120 سم",
    material: { nameAr: "مخمل ملكي وخشب معتق", slug: "velvet" },
    technique: { nameAr: "خط ثلث مركب وتذهيب عيار 24", slug: "thuluth-gilding" },
  },
  {
    id: "work-2",
    titleAr: "أثر البلور — حفر مجهري على الزجاج",
    titleEn: "Glass Imprint Crystalline",
    slug: "glass-imprint-crystalline",
    excerptAr: "حفر حروف كلاسيكية على الكريستال الشفاف مع انعكاسات ضوئية تجعل الحرف يطفو في فضاء القطعة.",
    descriptionAr: "تقنية فريدة طورها الخطاط سهيل نصر تجمع بين شفافية الكريستال وحدّة الإزميل الحفري اليدوي.",
    coverImage: "/images/hero-glass.jpg",
    featured: true,
    year: 2024,
    dimensions: "45 × 35 سم",
    material: { nameAr: "الزجاج", slug: "glass" },
    technique: { nameAr: "حفر يدوي دقيق", slug: "glass-engraving" },
  },
  {
    id: "work-3",
    titleAr: "نبض الخشب — حرق حراري على خشب الجوز",
    titleEn: "Wood Pulse Walnut Etching",
    slug: "wood-pulse-walnut",
    excerptAr: "تفاعل حراري بين عروق الخشب الطبيعي وانحناءات خط النسخ والديواني الجلي.",
    descriptionAr: "نقش بالحرق اليدوي على أخشاب طبيعية معتقة يبرز التدرجات اللونية الطبيعية للحرف.",
    coverImage: "/images/hero-wood.jpg",
    featured: true,
    year: 2023,
    dimensions: "60 × 40 سم",
    material: { nameAr: "الخشب", slug: "wood" },
    technique: { nameAr: "حرق يدوي وتعتيق", slug: "wood-burning" },
  },
  {
    id: "work-4",
    titleAr: "سبحة السكينة — نقش يدوي على البكلايت",
    titleEn: "Serenity Prayer Beads Inscription",
    slug: "serenity-prayer-beads",
    excerptAr: "نقش مجهري دقيق لأسماء وإهداءات على حبات وشاهد سبحة فاخرة من الكهرمان والبكلايت.",
    descriptionAr: "كتابة دقيقة بحجم رأس الدبوس تنفذ بعدسات تكبير متقدمة لتخليد الأسماء على السبح.",
    coverImage: "/images/hero-beads.jpg",
    featured: true,
    year: 2024,
    dimensions: "33 حبة مخصصة",
    material: { nameAr: "السبح", slug: "prayer-beads" },
    technique: { nameAr: "نقش مجهري يدوي", slug: "micro-engraving" },
  },
  {
    id: "work-5",
    titleAr: "كوب الهيبة — خط مخصص على الخزف الأسود",
    titleEn: "The Prestige Cup",
    slug: "prestige-cup",
    excerptAr: "تخطيط فني مخصص بحبر الذهب المقاوم على خزف فاخر للإهداءات الرسمية.",
    descriptionAr: "تصميم حروف مخصصة على الخزف مع معالجة حرارية تضمن ثبات الحبر الذهبي للأبد.",
    coverImage: "/images/craft-action.jpg",
    featured: true,
    year: 2024,
    dimensions: "ارتفاع 12 سم",
    material: { nameAr: "الأكواب", slug: "cups" },
    technique: { nameAr: "تخطيط يدوي بالذهب", slug: "gold-lettering" },
  },
  {
    id: "work-6",
    titleAr: "حين يصبح الحرف أثراً — ورق طبيعي مقهر",
    titleEn: "When The Letter Becomes An Imprint",
    slug: "letter-becomes-imprint",
    excerptAr: "عمل أصيل بالخط الكوفي الفاطمي والثلث على ورق قطني يدوي معتق وأحبار نباتية نقية.",
    descriptionAr: "تكوين خطي كلاسيكي على الورق الطبيعي المعالج بأساليب التقهير العثمانية والمغربية الأصيلة.",
    coverImage: "/images/suhail-calligraphy-hero.jpg",
    featured: true,
    year: 2023,
    dimensions: "70 × 50 سم",
    material: { nameAr: "الورق الطبيعي", slug: "paper" },
    technique: { nameAr: "قصب وأحبار تقليدية", slug: "traditional-reed" },
  },
];

export const FALLBACK_MATERIALS = [
  { id: "m-glass", nameAr: "الزجاج", nameEn: "Glass", slug: "glass", descriptionAr: "حفر يدوي دقيق وانعكاسات ضوئية شفافة تجعل الحرف يطفو في فضاء القطعة.", _count: { works: 4 } },
  { id: "m-wood", nameAr: "الخشب", nameEn: "Wood", slug: "wood", descriptionAr: "حرق وحفر وتذهيب على أخشاب طبيعية معتقة تتفاعل عروقها الدافئة مع انحناءات الحرف.", _count: { works: 5 } },
  { id: "m-velvet", nameAr: "المخمل", nameEn: "Velvet", slug: "velvet", descriptionAr: "أثر عميق وملمس غني وثير يمنح التركيبات الخطية فخامة بصرية وظلالاً متباينة.", _count: { works: 3 } },
  { id: "m-beads", nameAr: "السبح", nameEn: "Prayer Beads", slug: "prayer-beads", descriptionAr: "كتابة مجهرية دقيقة على حبات وشواهد السبح النادرة تخلد الأسماء والإهداءات.", _count: { works: 4 } },
  { id: "m-cups", nameAr: "الأكواب", nameEn: "Cups", slug: "cups", descriptionAr: "تخطيط فني مخصص ونقش يدوي على الأكواب والخزف ليرافق الحرف تفاصيل اليوم المتجددة.", _count: { works: 3 } },
  { id: "m-paper", nameAr: "الورق الطبيعي", nameEn: "Fine Paper", slug: "paper", descriptionAr: "ورق مقهر يدوي معتق وأحبار نباتية نقية تتبع أصول وقواعد السطور الكلاسيكية.", _count: { works: 6 } },
];

export const FALLBACK_JOURNAL = [
  {
    id: "j-1",
    titleAr: "فلسفة الحفر على الزجاج: حين يلتقي الضوء بالحرف العربي",
    slug: "philosophy-of-glass-calligraphy",
    excerptAr: "تأملات في التعامل مع شفافية البلور وصلابته لنحت نصوص تعيش مع تغيرات النور والظل.",
    category: "فلسفة الحرف",
    publishedAt: new Date(),
    author: "سهيل نصر",
    coverImage: "/images/hero-glass.jpg",
  },
  {
    id: "j-2",
    titleAr: "حرق الخشب والحرف الكوفي: حوار النار والأصالة",
    slug: "wood-burning-and-kufic-script",
    excerptAr: "كيف تمنح حرارة أداة الحرق بعداً روحياً لعروق الخشب الطبيعي لتجسيد هندسة الخط الكوفي.",
    category: "تقنيات الأتيليه",
    publishedAt: new Date(),
    author: "سهيل نصر",
    coverImage: "/images/hero-wood.jpg",
  },
];

export const FALLBACK_SOCIAL = [
  {
    id: "s-1",
    provider: "snapchat",
    title: "يوميات الأتيليه ونقش مباشر على حبات السبحة",
    url: "https://www.snapchat.com/@Sohilnasr7",
    thumbnail: "/images/hero-beads.jpg",
    description: "كواليس كتابة الإهداءات الشخصية الدقيقة في ستوديو الرياض.",
  },
  {
    id: "s-2",
    provider: "instagram",
    title: "استعراض عمل رؤية ٢٠٣٠ التذكاري بالذهب الخالص",
    url: "https://www.instagram.com/sohil.nassr",
    thumbnail: "/images/suhail-vision-2030.png",
    description: "تفاصيل تذهيب الحروف والتراكيب المركبة.",
  },
];
